#node-emulator2.toml
[server]
port = 5561

[node]
detect-drivers = false
override-max-sessions = true
max-sessions = 3

#[[node.driver-configuration]]
#max-sessions = 3

[relay]
url = "http://127.0.0.1:4733"
status-endpoint = "/status"
configs = [
    "1", "{\"platformName\": \"Android\",\"appium:deviceName\": \"l7bunn4h69lfxc8d\", \"appium:automationName\": \"UiAutomator2\"}"
]