#node-emulator1.toml
[server]
port = 5559

[node]
detect-drivers = false

[relay]
url = "http://127.0.0.1:4723"
status-endpoint = "/status"
configs = [
    "1", "{\"appium:platformName\": \"Android\",\"appium:deviceName\": \"emulator-5554\", \"appium:automationName\": \"UiAutomator2\"}"
]