[server]
port = 5561

[node]
detect-drivers = false

[relay]
url = "http://127.0.0.1:4725"
status-endpoint = "/status"
configs = [
    "1", "{\"appium:platformName\": \"Android\",\"appium:deviceName\": \"emulator-5556\", \"appium:automationName\": \"UiAutomator2\"}"
]